---
name: ManpagePublish

on:
    push:
    # paths:
    #   - ospackage/man/*
    pull_request:

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write


# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
    group: "pages"
    cancel-in-progress: false


jobs:
    manpage:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest

        steps:
            - name: Install pandoc
              run: sudo apt install -y pandoc

            - name: Check pandoc version
              run:  pandoc --version

            - uses: actions/checkout@v4

            - name: Show checkout
              run: |
                ls
                echo "---"
                ls ospackage/man

            - name: Create output directory
              run: mkdir manpages 2>/dev/null  || true

            - name: Convert Manpages > HTML
              run: |
                for manpage in ospackage/man/*.?; do
                  m=${manpage%.*}
                  base=${m##*/}
                  pandoc --from man --to html < ${manpage} > manpages/${base}.html
                done

            - name: List content of output directory
              run: ls manpages/

            # - name: Upload artifact
            #   uses: actions/upload-artifact@v4
            #   with:
            #     name: manpages
            #     path: manpages/
            #     retention-days: 1

            - name: Setup Pages
              uses: actions/configure-pages@v4

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  # Upload content of manpages directory
                  path: manpages/*.html

            - name: Deploy to GH Pages
              id: deployment
              uses: actions/deploy-pages@v4

            - name: Output GH Pages URL
              run:
                echo "github-pages=${github-pages}" >> "$GITHUB_OUTPUT"
