name: ManpagePublish

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    manpage:
        runs-on: ubuntu-latest

        steps:
            - name: Print hello
              run: echo "It works"